
#TODO: 做一个从log当中抽取运行信息并且绘图的脚本

'''

例如从下面这些信息中抽取这整数，并且绘图

seek for bad cube...
Adding frame 1...
check for Induction now...
New Frame 1:
seek for bad cube...
Adding frame 2...
check for Induction now...
check for Induction now...
New Frame 2:
seek for bad cube...
Adding frame 3...
check for Induction now...
check for Induction now...
check for Induction now...
New Frame 3:
seek for bad cube...
Adding frame 4...
check for Induction now...
check for Induction now...
check for Induction now...
check for Induction now...
New Frame 4:
seek for bad cube...
Adding frame 5...
check for Induction now...
check for Induction now...
check for Induction now...
check for Induction now...
check for Induction now...
New Frame 5:
seek for bad cube...
Adding frame 6...
check for Induction now...
check for Induction now...
check for Induction now...
check for Induction now...
check for Induction now...
check for Induction now...
Fond inductive invariant:

Done in time
TIME CONSUMING: 2291seconds

'''